---

- include: locale.yml

- include: host.yml

- include: proxy.yml
  when: proxy is defined


# - name: "Build hosts file"
#   lineinfile: dest=/etc/hosts regexp='.*{{item}} .*$' line="{{hostvars[item]['ansible_host']}} {{item}}" state=present
#   with_items: "{{ groups['all'] }}"



- name: Installation des packets utiles
  become: yes
  apt: update_cache=yes name={{ item }} cache_valid_time=604800 # 7 jours
  with_items: "{{ packages }}"

- name: Enable ls shorcuts
  become: 
  lineinfile: dest=/home/pirate/.bashrc regexp="{{ item.regexp }}" line="{{ item.line }}"
  with_items:
    - {regexp: 'alias ll', line: 'alias ll="ls -lh"'}
    - {regexp: 'alias la', line: 'alias la="ls -la"'}
