version: "3.0"
services:
  app:
    image: node:alpine
    volumes:
      - ../print-hostname:/usr/src/app
    command: node /usr/src/app/app.js
    labels:
      traefik.port: "80"
      traefik.frontend.rule: "Host:127.0.0.1,localhost,hp1410p002.ensg.eu"
      traefik.backend: "app"
    depends_on: 
      - lb
  lb:
    image: traefik
    ports:
      - "8080:8080"
      - "8081:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "false"
    command: --docker --docker.watch --web